version: '3.8'
services:
  frontend:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_NAME}:frontend_latest
    ports:
      - "3000:80"
    networks:
      - examninja-network
    depends_on:
      - backend

  backend:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_NAME}:backend_latest
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/exam_ninja
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - examninja-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exam_ninja
    ports:
      - "3307:3306"
    networks:
      - examninja-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  examninja-network:
    driver: bridge

volumes:
  mysql_data:
